import requests

response = requests.get('https://opentdb.com/api.php?amount=20&type=boolean')
q_data = response.json()
data = q_data['results']


# data = [
#     {"category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "easy",
#      "question": "In the &quot;Shrek&quot; film franchise, Donkey is played by Eddie Murphy.",
#      "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
#      "question": "In the 1988 film &quot;Akira&quot;, Tetsuo ends up destroying Tokyo.",
#      "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
#      "question": "The movie &quot;The Nightmare before Christmas&quot; was all done with physical objects.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "&quot;Undertale&quot; is an RPG created by Toby Fox and released in 2015.",
#      "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
#      "question": "A universal set, or a set that contains all sets, exists.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "The game &quot;Battlefield 1&quot; takes place during World War I.", "correct_answer": "True",
#      "incorrect_answers": ["False"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
#                                        "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
#                                        "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"category": "Geography", "type": "boolean", "difficulty": "easy",
#      "question": "Ottawa is the capital of Canada.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
#      "question": "The card game &quot;Munchkin&quot; won the 2001 Origins Award for Best Traditional Card Game.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
#      "question": "Samuel L. Jackson had the words, &#039;Bad Motherf*cker&#039; in-scripted on his lightsaber during the filming of Star Wars.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "Pluto is a planet.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
#      "question": "The alternative rock band, They Might Be Giants, released their album &#039;Flood&#039; in 1990. ",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#      "question": "&quot;HTML&quot; stands for Hypertext Markup Language.", "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#      "question": "Time on Computers is measured via the EPOX System.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
#      "question": "A Saxophone is a brass instrument.", "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
#      "question": "An exothermic reaction is a chemical reaction that releases energy by radiating electricity.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"category": "History", "type": "boolean", "difficulty": "easy",
#      "question": "In World War ll, Great Britian used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy\/D-day landing.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "History", "type": "boolean", "difficulty": "easy",
#      "question": "Kublai Khan is the grandchild of Genghis Khan?", "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "&quot;Metal Gear Solid 3: Snake Eater&quot; was released in 2004.", "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "The ghosts in &quot;Pac-Man&quot; and &quot;Ms. Pac-Man&quot; have completely different behavior.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "In &quot;Need for Speed: Porsche Unleashed&quot;, the player can only drive cars manufactured by Porsche.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
#      "question": "An isosceles triangle has two sides of equal length as opposed to three.",
#      "correct_answer": "True",
#      "incorrect_answers": ["False"]}, {"category": "Geography", "type": "boolean", "difficulty": "easy",
#                                        "question": "There is an island in Japan called \u014ckunoshima, A.K.A. &quot;Rabbit Island&quot;, so named because of it&#039;s huge population of rabbits.",
#                                        "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
#      "question": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
#      "correct_answer": "False", "incorrect_answers": ["True"]}
# ]
